name: scrollable_positioned_list
description: Stub for scrollable_positioned_list on HarmonyOS
version: 0.0.1
publish_to: 'none'

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
